Bytes <- NoNul: "No NUL character"
NoNul <- Line: "No CR or LF"
Line <- Word: "No spaces"
Word <- Arg: "Non-empty; no leading :"
Arg <- Cmd: "Only uppercase ASCII letters"
Arg <- Key: "No = or ;"
Arg <- Nick: "No ! or @"
Arg <- User: "No @ or %"
