image: archlinux # We need rustup, and Arch happily packages it.
packages:
  - rustup
sources:
  - https://git.sr.ht/~daemoness/vinezombie
environment:
  CARGO_TERM_COLOR: always
tasks:
  - setup: |
      rustup install 1.70
  - build-min: |
      cd vinezombie
      cargo build --no-default-features --message-format short
  - build-min-client: |
      cd vinezombie
      cargo build --no-default-features --features client --message-format short
  - build-default: |
      cd vinezombie
      cargo build --message-format short
  - build-max: |
      cd vinezombie
      cargo build --all-features --message-format short
  - test: |
      cd vinezombie
      cargo test --all-features
  - lint: |
      cd vinezombie
      cargo clippy --all-features
  - fmt: |
      cd vinezombie
      cargo fmt --check
