[package]
name = "vinezombie"
version = "0.1.0"
edition = "2021"

license = "GPL-3.0-only"
description = "An abstracting IRCv3 library"
repository = "https://github.com/TheDaemoness/vinezombie"
readme = "README.md"
keywords = ["irc", "ircv3"]
categories = ["network-programming", "parser-implementations"]

# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = { version = "0.13.1", optional = true }
serde = { version = "1.0.164", features = ["derive"], optional = true }
tokio = { version = "1.28.2", features = ["io-util"], optional = true }
whoami = { version = "1.3.0", optional = true }

[features]
default = ["abstract", "base64", "client"]
abstract = ["ircmsg", "state"]
client = ["ircmsg"]
ircmsg = []
state = []

[dev-dependencies]
env_logger = "0.10.0"
log = "0.4.18"

# [[example]]
# name = "hello-libera"
