[package]
name = "vinezombie"
version = "0.1.0"
edition = "2021"

license = "GPL-3.0-only"
description = "A modular IRCv3 client library"
homepage = "https://sr.ht/~daemoness/vinezombie/"
repository = "https://git.sr.ht/~daemoness/vinezombie"
readme = "README.md"
keywords = ["irc", "ircv3"]
categories = ["network-programming", "parser-implementations"]

# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = { version = "0.13.1", optional = true }
log = { version = "0.4.17", optional = true }
serde = { version = "1.0.164", features = ["derive"], optional = true }
tokio = { version = "1.28.2", features = ["io-util"], optional = true }
whoami = { version = "1.3.0", optional = true }

[dev-dependencies]
env_logger = "0.9.3"

[features]
default = ["log", "tokio", "base64"]

# [[example]]
# name = "hello-libera"
