[package]
name = "vinezombie"
version = "0.1.0"
edition = "2021"

license = "GPL-3.0-only"
description = "An abstracting IRCv3 library"
repository = "https://github.com/TheDaemoness/vinezombie"
readme = "README.md"
keywords = ["irc", "ircv3"]
categories = ["network-programming", "parser-implementations"]

# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = { version = "0.21.2", optional = true }
rustls = { version = "0.21.2", optional = true, features = ["dangerous_configuration"] }
rustls-native-certs = { version = "0.6.3", optional = true }
rustls-pemfile = { version = "1.0.2", optional = true }
serde = { version = "1.0.164", features = ["derive", "rc"], optional = true }
tokio = { version = "1.28.2", features = ["io-util"], optional = true }
whoami = { version = "1.3.0", optional = true }
zeroize = { version = "1.6.0", optional = true }

[features]
default = ["abstract", "base64", "client", "tls"]
abstract = ["ircmsg", "state"]
client = ["ircmsg"]
ircmsg = []
native = []
state = []
tls = ["dep:rustls", "dep:rustls-native-certs", "dep:rustls-pemfile", "native"]

[dev-dependencies]
env_logger = "0.10.0"
log = "0.4.18"

# [[example]]
# name = "hello-libera"
