direction: up

...@rustdoc/strings

Bytes.shape: class
NoNul.shape: class
Line.shape: class 
Word.shape: class
Arg.shape: class 
Nick.shape: class 
User.shape: class 
Cmd.shape: class 
Key.shape: class
